.TH "_particleT" 3 "Sat Jul 2 2016" "Version 1.00" "3D FPS Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_particleT \- Defines an alias representing the particle t\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <particle\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBvisible\fP"
.br
.RI "\fItrue to show, false to hide\&. \fP"
.ti -1c
.RI "int \fBFirstLifeTime\fP"
.br
.RI "\fIThe first life time\&. \fP"
.ti -1c
.RI "\fBvector3d\fP \fBpositionInAir\fP"
.br
.RI "\fIThe position in air\&. \fP"
.ti -1c
.RI "\fBvector3d\fP \fBpositionOnGround\fP"
.br
.RI "\fIThe position ground\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Defines an alias representing the particle t\&. 


.SH "Member Data Documentation"
.PP 
.SS "int _particleT::FirstLifeTime"

.PP
The first life time\&. 
.SS "\fBvector3d\fP _particleT::positionInAir"

.PP
The position in air\&. 
.SS "\fBvector3d\fP _particleT::positionOnGround"

.PP
The position ground\&. 
.SS "bool _particleT::visible"

.PP
true to show, false to hide\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 3D FPS Game from the source code\&.
