.TH "_particleSystemT" 3 "Sat Jul 2 2016" "Version 1.00" "3D FPS Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_particleSystemT \- Defines an alias representing the particle system t\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <particle\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBGroundHeight\fP"
.br
.RI "\fIHeight of the ground\&. \fP"
.ti -1c
.RI "float \fBmaxParticleHeight\fP"
.br
.RI "\fIThe maximum particle height\&. \fP"
.ti -1c
.RI "int \fBmaxParticleLifeTime\fP"
.br
.RI "\fIThe maximum particle life time\&. \fP"
.ti -1c
.RI "int \fBwidth\fP"
.br
.RI "\fIGets the height\&. \fP"
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBnumber\fP"
.br
.RI "\fINumber of\&. \fP"
.ti -1c
.RI "float \fBspeed\fP"
.br
.RI "\fIThe speed\&. \fP"
.ti -1c
.RI "float \fBsize\fP"
.br
.RI "\fIThe size\&. \fP"
.ti -1c
.RI "\fBparticleT\fP * \fBparticles\fP"
.br
.RI "\fIThe particles\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Defines an alias representing the particle system t\&. 


.SH "Member Data Documentation"
.PP 
.SS "float _particleSystemT::GroundHeight"

.PP
Height of the ground\&. 
.SS "float _particleSystemT::maxParticleHeight"

.PP
The maximum particle height\&. 
.SS "int _particleSystemT::maxParticleLifeTime"

.PP
The maximum particle life time\&. 
.SS "int _particleSystemT::number"

.PP
Number of\&. 
.SS "\fBparticleT\fP* _particleSystemT::particles"

.PP
The particles\&. 
.SS "float _particleSystemT::size"

.PP
The size\&. 
.SS "float _particleSystemT::speed"

.PP
The speed\&. 
.SS "int _particleSystemT::width"

.PP
Gets the height\&. The height\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 3D FPS Game from the source code\&.
