.TH "BulletT" 3 "Sat Jul 2 2016" "Version 1.00" "3D FPS Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BulletT \- Defines an alias representing the bullet\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <particle\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBulletT\fP (\fBvector3d\fP \fBpositionInAir\fP, \fBvector3d\fP \fBdestination\fP, \fBvector3d\fP \fBdirection\fP, float \fBsize\fP, float \fBspeed\fP, bool \fBboom\fP, float \fBtimer\fP)"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvector3d\fP \fBpositionInAir\fP"
.br
.RI "\fIThe position in air\&. \fP"
.ti -1c
.RI "\fBvector3d\fP \fBdestination\fP"
.br
.RI "\fIDestination for the\&. \fP"
.ti -1c
.RI "\fBvector3d\fP \fBdirection\fP"
.br
.RI "\fIThe direction\&. \fP"
.ti -1c
.RI "float \fBsize\fP"
.br
.RI "\fIThe size\&. \fP"
.ti -1c
.RI "float \fBspeed\fP"
.br
.RI "\fIThe speed\&. \fP"
.ti -1c
.RI "bool \fBboom\fP"
.br
.RI "\fItrue to boom\&. \fP"
.ti -1c
.RI "int \fBlife\fP"
.br
.RI "\fIThe life\&. \fP"
.ti -1c
.RI "int \fBmaxTimer\fP"
.br
.RI "\fIThe maximum timer\&. \fP"
.ti -1c
.RI "int \fBtimer\fP"
.br
.RI "\fIThe timer\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Defines an alias representing the bullet\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "BulletT::BulletT (\fBvector3d\fP positionInAir, \fBvector3d\fP destination, \fBvector3d\fP direction, float size, float speed, bool boom, float timer)\fC [inline]\fP"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpositionInAir\fP The position in air\&. 
.br
\fIdestination\fP Destination for the\&. 
.br
\fIdirection\fP The direction\&. 
.br
\fIsize\fP The size\&. 
.br
\fIspeed\fP The speed\&. 
.br
\fIboom\fP true to boom\&. 
.br
\fItimer\fP The timer\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "bool BulletT::boom"

.PP
true to boom\&. 
.SS "\fBvector3d\fP BulletT::destination"

.PP
Destination for the\&. 
.SS "\fBvector3d\fP BulletT::direction"

.PP
The direction\&. 
.SS "int BulletT::life"

.PP
The life\&. 
.SS "int BulletT::maxTimer"

.PP
The maximum timer\&. 
.SS "\fBvector3d\fP BulletT::positionInAir"

.PP
The position in air\&. 
.SS "float BulletT::size"

.PP
The size\&. 
.SS "float BulletT::speed"

.PP
The speed\&. 
.SS "int BulletT::timer"

.PP
The timer\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 3D FPS Game from the source code\&.
