.TH "collisionsphere" 3 "Sat Jul 2 2016" "Version 1.00" "3D FPS Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
collisionsphere \- A collisionsphere\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <collisionsphere\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcollisionsphere\fP (\fBvector3d\fP c, float rad)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "\fBcollisionsphere\fP ()"
.br
.RI "\fIDefault constructor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBr\fP"
.br
.RI "\fIThe float to process\&. \fP"
.ti -1c
.RI "\fBvector3d\fP \fBcenter\fP"
.br
.RI "\fIThe center\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A collisionsphere\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "collisionsphere::collisionsphere (\fBvector3d\fP c, float rad)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIc\fP The \fBvector3d\fP to process\&. 
.br
\fIrad\fP The radians\&. 
.RE
.PP

.SS "collisionsphere::collisionsphere ()"

.PP
Default constructor\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBvector3d\fP collisionsphere::center"

.PP
The center\&. 
.SS "float collisionsphere::r"

.PP
The float to process\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 3D FPS Game from the source code\&.
