.TH "coordinate" 3 "Sat Jul 2 2016" "Version 1.00" "3D FPS Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coordinate \- A coordinate\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <objectloader\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcoordinate\fP (float a, float b, float c)"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.RI "\fIGets the z coordinate\&. \fP"
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A coordinate\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "coordinate::coordinate (float a, float b, float c)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP The float to process\&. 
.br
\fIb\fP The float to process\&. 
.br
\fIc\fP The float to process\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "float coordinate::x"

.PP
Gets the z coordinate\&. The z coordinate\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 3D FPS Game from the source code\&.
