.TH "face" 3 "Sat Jul 2 2016" "Version 1.00" "3D FPS Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
face \- A face\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <objectloader\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBface\fP (int facen, int f1, int f2, int f3, int t1, int t2, int t3, int m)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "\fBface\fP (int facen, int f1, int f2, int f3, int f4, int t1, int t2, int t3, int t4, int m)"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBfacenum\fP"
.br
.RI "\fIThe facenum\&. \fP"
.ti -1c
.RI "bool \fBfour\fP"
.br
.RI "\fItrue to four\&. \fP"
.ti -1c
.RI "int \fBfaces\fP [4]"
.br
.RI "\fIThe faces[ 4]\&. \fP"
.ti -1c
.RI "int \fBtexcoord\fP [4]"
.br
.RI "\fIThe texcoord[ 4]\&. \fP"
.ti -1c
.RI "int \fBmat\fP"
.br
.RI "\fIThe matrix\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A face\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "face::face (int facen, int f1, int f2, int f3, int t1, int t2, int t3, int m)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfacen\fP The facen\&. 
.br
\fIf1\fP The first int\&. 
.br
\fIf2\fP The second int\&. 
.br
\fIf3\fP The third int\&. 
.br
\fIt1\fP The first int\&. 
.br
\fIt2\fP The second int\&. 
.br
\fIt3\fP The third int\&. 
.br
\fIm\fP The int to process\&. 
.RE
.PP

.SS "face::face (int facen, int f1, int f2, int f3, int f4, int t1, int t2, int t3, int t4, int m)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfacen\fP The facen\&. 
.br
\fIf1\fP The first int\&. 
.br
\fIf2\fP The second int\&. 
.br
\fIf3\fP The third int\&. 
.br
\fIf4\fP The fourth int\&. 
.br
\fIt1\fP The first int\&. 
.br
\fIt2\fP The second int\&. 
.br
\fIt3\fP The third int\&. 
.br
\fIt4\fP The fourth int\&. 
.br
\fIm\fP The int to process\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "int face::facenum"

.PP
The facenum\&. 
.SS "int face::faces[4]"

.PP
The faces[ 4]\&. 
.SS "bool face::four"

.PP
true to four\&. 
.SS "int face::mat"

.PP
The matrix\&. 
.SS "int face::texcoord[4]"

.PP
The texcoord[ 4]\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 3D FPS Game from the source code\&.
