.TH "tagBITMAPINFOHEADER" 3 "Sat Jul 2 2016" "Version 1.00" "3D FPS Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagBITMAPINFOHEADER \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DWORD \fBbiSize\fP"
.br
.ti -1c
.RI "LONG \fBbiWidth\fP"
.br
.ti -1c
.RI "LONG \fBbiHeight\fP"
.br
.ti -1c
.RI "WORD \fBbiPlanes\fP"
.br
.ti -1c
.RI "WORD \fBbiBitCount\fP"
.br
.ti -1c
.RI "DWORD \fBbiCompression\fP"
.br
.ti -1c
.RI "DWORD \fBbiSizeImage\fP"
.br
.ti -1c
.RI "LONG \fBbiXPelsPerMeter\fP"
.br
.ti -1c
.RI "LONG \fBbiYPelsPerMeter\fP"
.br
.ti -1c
.RI "DWORD \fBbiClrUsed\fP"
.br
.ti -1c
.RI "DWORD \fBbiClrImportant\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 3D FPS Game from the source code\&.
