.TH "tagFICOMPLEX" 3 "Sat Jul 2 2016" "Version 1.00" "3D FPS Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagFICOMPLEX \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FreeImage\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBr\fP"
.br
.RI "\fIreal part \fP"
.ti -1c
.RI "double \fBi\fP"
.br
.RI "\fIimaginary part \fP"
.in -1c
.SH "Detailed Description"
.PP 
Data structure for COMPLEX type (complex number) 

.SH "Author"
.PP 
Generated automatically by Doxygen for 3D FPS Game from the source code\&.
