.TH "tagRGBQUAD" 3 "Sat Jul 2 2016" "Version 1.00" "3D FPS Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagRGBQUAD \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BYTE \fBrgbBlue\fP"
.br
.ti -1c
.RI "BYTE \fBrgbGreen\fP"
.br
.ti -1c
.RI "BYTE \fBrgbRed\fP"
.br
.ti -1c
.RI "BYTE \fBrgbReserved\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for 3D FPS Game from the source code\&.
