.TH "texcoord" 3 "Sat Jul 2 2016" "Version 1.00" "3D FPS Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
texcoord \- A texcoord\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <objectloader\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtexcoord\fP (float a, float b)"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBu\fP"
.br
.RI "\fIGets the v\&. \fP"
.ti -1c
.RI "float \fBv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A texcoord\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "texcoord::texcoord (float a, float b)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP The float to process\&. 
.br
\fIb\fP The float to process\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "float texcoord::u"

.PP
Gets the v\&. The v\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 3D FPS Game from the source code\&.
